version: '3.8'

services:

  db:
    image: mysql
    container_name: mySQL-1
    # command: insert input command for autoloading script/db creation
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysqldata: